# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 5002

# Run the Flask application
# Use gunicorn for a production-ready WSGI server
CMD ["gunicorn", "--bind", "0.0.0.0:5002", "app:app"]
