name: Deploy

on:
  workflow_run:
    workflows: ["AWS Unit Tests"]
    types:
      - completed # This workflow will trigger when the specified workflow is 'completed'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop Containers on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd AWS/MarketPlace/backend
          sudo docker compose down
          sudo docker stop redis-test

    - name: List GitHub Files (local repository content)
      run: ls

    - name: Delete existing 'AWS' folder on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          ls
          echo "Deleting AWS on EC2..."
          rm -r AWS || true
          echo "Deletion complete."

    - name: Upload new 'AWS' folder to EC2
      uses: appleboy/scp-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "AWS/"
        target: "/home/ubuntu/"

    - name: Verify Uploaded Files on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          echo "Listing files in the home directory:"
          ls
          AWS_DIR="AWS"
          if [[ ! -d "$AWS_DIR" ]]; then
            echo "Error: Directory '$AWS_DIR' not found."
            exit 1
          fi
          echo "Directory '$AWS_DIR' found. Proceeding with script..."

    - name: Start Containers
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd AWS/MarketPlace/backend
          sudo docker compose up --build -d
          sudo docker start redis-test
