name: EC2 File Upload

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - 'docs/**'

  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  upload_aws_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List GitHub Files (local repository content)
      run: ls

    - name: Delete existing 'AWS' folder on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 34.221.214.9
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          ls
          echo "Deleting /home/ubuntu/AWS on EC2..."
          rm -r /home/ubuntu/AWS || true
          echo "Deletion complete."

    - name: Upload new 'AWS' folder to EC2
      uses: appleboy/scp-action@master
      with:
        host: 34.221.214.9
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "AWS/"
        target: "/home/ubuntu/"

    - name: Verify Uploaded Files on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 34.221.214.9
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          echo "Listing files in the uploaded /home/ubuntu/AWS/ directory:"
          ls /home/ubuntu/
          echo "File upload and verification complete."