name: Deploy

on:
  workflow_run:
    workflows: ["AWS Unit Tests"]
    types:
      - completed # This workflow will trigger when the specified workflow is 'completed'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

env:
  HOST_IP: 35.94.30.150

jobs:
  Deploy-on-EC2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Stop Running Containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop redis-test
          cd SMS_LLM/AWS/MarketPlace/backend
          sudo docker compose down

    - name: List running containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker ps

    - name: Git Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM
          git pull origin main

    - name: Start Containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker start redis-test
          cd SMS_LLM/AWS/MarketPlace/backend
          sudo docker compose up --build -d

    - name: List running containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker ps