name: Marketplace Security CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - 'docs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - 'docs/**'

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.89.2
        with:
          args: --fail-on-detect