name: Post Deploy

on:
  workflow_run:
    workflows: ["Deploy"] # Trigger when "Deploy" workflow completes
    types:
      - completed # Listen for completion (success or failure)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

env:
  HOST_IP: 44.242.207.112

jobs:
  test-aws:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM/AWS
          source venv/bin/activate
          pip install -r requirements.txt

    - name: Run function calling tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM/AWS
          set -a
          source .env
          source Test/.env
          set +a
          source venv/bin/activate
          python Test/function_calling_test.py

    - name: Run caching tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM/AWS
          set -a
          source .env
          set +a
          source venv/bin/activate
          python Test/cache_test.py

    - name: Run add_cache tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM/AWS
          set -a
          source .env
          set +a
          source venv/bin/activate
          chmod +x Test/add_cache_test.sh
          ./Test/add_cache_test.sh

    - name: Run main test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd SMS_LLM/AWS
          set -a
          source .env
          set +a
          source venv/bin/activate
          python Test/test.py