name: Post Deployment

on:
  workflow_run:
    workflows: ["Deploy"] # Trigger when "Deploy" workflow completes
    types:
      - completed # Listen for completion (success or failure)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  test-aws:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd AWS
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: List running containers
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker ps

    - name: Run function calling tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          source AWS/venv/bin/activate
          python AWS/Test/function_calling_test.py

    - name: Print database
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd AWS/MarketPlace/backend
          sudo docker compose exec db psql -U user marketplace_db -c "SELECT * FROM listings;"

    - name: Run caching tests
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          source AWS/venv/bin/activate
          python AWS/Test/cache_test.py

    - name: Run add_cache tests
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          source AWS/venv/bin/activate
          chmod +x AWS/Test/add_cache_test.sh
          ./AWS/Test/add_cache_test.sh

    - name: Run main test
      env:
        API_GATEWAY_URL: https://7029iecp6i.execute-api.us-west-2.amazonaws.com/v1/process-voice
      uses: appleboy/ssh-action@master
      with:
        host: 54.214.58.255
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          source AWS/venv/bin/activate
          python AWS/Test/test.py