name: Post Deploy

on:
  workflow_run:
    workflows: ["Deploy"] # Trigger when "Deploy" workflow completes
    types:
      - completed # Listen for completion (success or failure)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  test-aws:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Restore cached pip installations
      id: cache-restore
      uses: actions/cache@v4
      with:
        path: AWS/venv
        key: ${{ runner.os }}-pip-${{ hashFiles('AWS/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run function calling tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        cd AWS
        set -a
        source .env
        set +a
        source venv/bin/activate
        python Test/function_calling_test.py

    - name: Run caching tests
      run: |
        cd AWS
        set -a
        source .env
        set +a
        source venv/bin/activate
        python Test/cache_test.py

    - name: Run main test
      run: |
        cd AWS
        set -a
        source .env
        set +a
        source venv/bin/activate
        python Test/test.py