name: Python Specific Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Set PYTHONPATH and Run specific test file
      run: |
        # Add the 'AWS' directory to PYTHONPATH
        # This ensures test_my_module.py can find my_module.py
        export PYTHONPATH=$PYTHONPATH:$(pwd)/AWS

        # Run only the specified test file by its full path
        python AWS/Test/test_my_module.py