name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AWS/requirements.txt

    - name: Start Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose up -d

    - name: List running containers (initial check)
        run: |
          docker ps

    - name: Wait for PostgreSQL to be ready
      run: |
        chmod +x AWS/Test/wait_for_db.sh
        ./AWS/Test/wait_for_db.sh

    - name: Check using /get_all_listings
      run: |
        chmod +x AWS/Test/get_all_listings.sh
        ./AWS/Test/get_all_listings.sh

    - name: Run tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python AWS/Test/function_calling_test.py

    - name: Stop Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose down
        sudo systemctl stop postgresql
