name: Python Unit Tests

on:
  push:
    branches:
      - main # or your default branch, e.g., master, develop
    paths-ignore:
      - 'README.md'
      - '**/*.md' # To ignore all markdown files
      - 'docs/**' # To ignore all files in a 'docs' directory

  pull_request:
    branches:
      - main # or your default branch
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AWS/requirements.txt

    - name: Start Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose up -d

    - name: Wait for PostgreSQL to be ready
      run: |
        chmod +x AWS/Test/wait_for_db.sh
        ./AWS/Test/wait_for_db.sh

    - name: Wait for app using /get_all_listings
      run: |
        chmod +x AWS/Test/get_all_listings.sh
        ./AWS/Test/get_all_listings.sh

    - name: List running containers
      run: |
        docker ps

    - name: Run function calling tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        FLASK_SERVER_BASE_URL: http://localhost:5000
      run: |
        python AWS/Test/function_calling_test.py

    - name: Print database
      run: |
        cd AWS/MarketPlace/backend
        sudo docker compose exec db psql -U user marketplace_db -c "SELECT * FROM listings;"

    - name: Stop Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose down
        sudo systemctl stop postgresql

    - name: Run Redis image in a container
      run: |
        docker run -d --name redis-test -p 6379:6379 redis:latest

    - name: Run caching tests
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_DB: 0
      run: |
        python AWS/Test/cache_test.py

    - name: Stop Redis container
      run: |
        docker stop redis-test

    - name: Run main test
      env:
        API_GATEWAY_URL: https://7029iecp6i.execute-api.us-west-2.amazonaws.com/v1/process-voice
      run: |
        python AWS/Test/test.py
