name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AWS/requirements.txt

    - name: Setup Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose up

    - name: Run AWS tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python AWS/Test/function_calling_test.py

    - name: Stop Marketplace backend
      run: |
        cd AWS/MarketPlace/backend
        docker compose down
        sudo systemctl stop postgresql
